server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:9080/auth
  realm: Application
  resource: springboot-keycloak
  public-client: true
  bearer-only: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: books-api
